sjsonnet/src/sjsonnet/Val.scala
sjsonnet/test/src/sjsonnet/EvaluatorTests.scala

https://github.com/databricks/sjsonnet/issues/5

Reject invalid parameters passed to a function

---

sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/resources/test_suite/stdlib.jsonnet

This PR adds three jsonnet std functions (with tests) to sjsonnet
@FUSAKLA

Add `std.parseJson`, `std.find` and `std.findSubstr`

---

sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/resources/test_suite/stdlib.jsonnet

Try to fix https://github.com/databricks/sjsonnet/issues/30

fix: std.substr gives substring with wrong length

---

sjsonnet/src/sjsonnet/Std.scala

Added a standard function to gzip the given data (String/Bytes Array) and return a Base64 encoded gzipped string back.
`std.gzip(...)`

Added GZip Standard Function

---

sjsonnet/src/sjsonnet/Std.scala

Added the String ReplaceAll method in Standard Library.

Added STD String ReplaceAll Method

---

sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/test/src-jvm/sjsonnet/ErrorTests.scala

Minor PR to fix a small mispelling in error messages

Fix mispelling of attempted in evaluator

---

sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/src/sjsonnet/StdStripCharsTests.scala

Addresses https://github.com/databricks/sjsonnet/issues/67 , https://github.com/databricks/sjsonnet/issues/80,

Strip Chars functions implemented

---

sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/src/sjsonnet/StdFlatMapTests.scala

https://github.com/databricks/sjsonnet/issues/80

std.flatMap implemented

---

build.sc
readme.md
sjsonnet/src/sjsonnet/Interpreter.scala

@lihaoyi-databricks Any dependencies we should bump?

Update for release 0.2.7

---

build.sbt
readme.md

update changelog and version

---

bench/src/main/scala/sjsonnet/OptimizerBenchmark.scala
bench/src/main/scala/sjsonnet/ParserBenchmark.scala
build.sc
sjsonnet/src-jvm-native/sjsonnet/Config.scala
sjsonnet/src-jvm-native/sjsonnet/SjsonnetMain.scala
sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/src/sjsonnet/Importer.scala
sjsonnet/src/sjsonnet/Interpreter.scala
sjsonnet/src/sjsonnet/Parser.scala
sjsonnet/src/sjsonnet/Settings.scala
sjsonnet/src/sjsonnet/Std.scala
sjsonnet/src/sjsonnet/Val.scala
sjsonnet/test/src/sjsonnet/EvaluatorTests.scala
sjsonnet/test/src/sjsonnet/ParserTests.scala
sjsonnet/test/src/sjsonnet/Std0150FunctionsTests.scala
sjsonnet/test/src/sjsonnet/TestUtils.scala

WIP to cut a stable 0.4.5. Just some last minute fixes and tweaks to ensure a smooth rollout within Databricks

Release 0.4.5

---

sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/src/sjsonnet/Std0150FunctionsTests.scala

Implement std.any and std.all (from 0.19 release of jsonnet)

implement std any all

---

sjsonnet/src-jvm-native/sjsonnet/Config.scala
sjsonnet/src-jvm-native/sjsonnet/SjsonnetMain.scala

- Remove leftovers from Mill (which the main was likely forked from)
- We don't have an interactive mode
- Allow for repeating flags

Clean up sjsonnet main file to allow for repeating flags

---

sjsonnet/src/sjsonnet/BaseCharRenderer.scala
sjsonnet/src/sjsonnet/BaseRenderer.scala
sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/src/sjsonnet/Format.scala
sjsonnet/src/sjsonnet/ReadWriter.scala
sjsonnet/src/sjsonnet/Std.scala
sjsonnet/src/sjsonnet/Val.scala
sjsonnet/test/resources/test_suite/stdlib.jsonnet
sjsonnet/test/src/sjsonnet/EvaluatorTests.scala
sjsonnet/test/src/sjsonnet/FormatTests.scala

Fix parseInt() not supporting Longs

---

sjsonnet/src/sjsonnet/BaseCharRenderer.scala
sjsonnet/src/sjsonnet/Renderer.scala
sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/resources/test_suite/stdlib.jsonnet
sjsonnet/test/resources/test_suite/stdlib_native.jsonnet

Specifically newline & key_val_sep.

Implement missing parameters to manifestJson

---

.github/workflows/pr-build.yaml
sjsonnet/test/src-jvm/sjsonnet/StdGzipTests.scala

- Add JDK17 actions
- Split actions into 1 per lang/jdk version

Add jdk17 build

---

sjsonnet/src/sjsonnet/Parser.scala
sjsonnet/test/resources/test_suite/text_block.jsonnet

Implement the |||- syntax per https://github.com/google/jsonnet/commit/5a4e8e34cc1fe841bdebb983646b9b9ae8fa8ca4 in sjsonnet

Implement |||- syntax in sjsonnet

---

sjsonnet/src/sjsonnet/Std.scala

Motivation:
Optimize objectRemoveKey

chore: optimize objectRemoveKey

---

sjsonnet/src/sjsonnet/Std.scala

https://github.com/databricks/sjsonnet/pull/285 exposed a bug in the implementation

Fix std.min/maxArray

---

sjsonnet/src/sjsonnet/Std.scala

https://github.com/databricks/sjsonnet/pull/285 exposed a bug in the implementation

Fix std.min/maxArray (#287)

---

sjsonnet/src/sjsonnet/Interpreter.scala

Motivation:
It was been forced soon.

chore: Make evaluator a simple val

---

sjsonnet/src/sjsonnet/Interpreter.scala

Motivation:
Clean up the code, and then the user can provide a static optimizer, too.
refs: https://github.com/databricks/sjsonnet/pull/294

chore: Extract createOptimizer method.

---

bench/src/main/scala/sjsonnet/OptimizerBenchmark.scala
bench/src/main/scala/sjsonnet/ProfilingEvaluator.scala
sjsonnet/src-js/sjsonnet/SjsonnetMain.scala
sjsonnet/test/src-jvm/sjsonnet/BufferedRandomAccessFileTests.scala

chore: Fix some warning.

---

sjsonnet/src-jvm-native/sjsonnet/SjsonnetMain.scala

Small typo preventing TLAs to work

fix typo with tlaBindings

---

sjsonnet/src/sjsonnet/Interpreter.scala

Motivation:
Fix the compilation warning.

chore: Remove externalVariable matching warning.

---

sjsonnet/src/sjsonnet/Parser.scala

Motivation:
Avoid the hashmap query when climb

chore: avoid look up hashmap when query precedence

---

sjsonnet/src-js/sjsonnet/SjsonnetMain.scala
sjsonnet/src-jvm-native/sjsonnet/Config.scala
sjsonnet/src-jvm-native/sjsonnet/OsPath.scala
sjsonnet/src/sjsonnet/Expr.scala
sjsonnet/src/sjsonnet/ExternalVariable.scala
sjsonnet/src/sjsonnet/Format.scala
sjsonnet/src/sjsonnet/Importer.scala
sjsonnet/src/sjsonnet/Renderer.scala
sjsonnet/src/sjsonnet/Val.scala
sjsonnet/test/src/sjsonnet/DummyPath.scala

Motivation:
This will help hotspot a little.

chore: Make case classes final.

---

sjsonnet/test/src/sjsonnet/ValLiteralFunctionTest.scala

Add the missing test about it, I was having lunch:)
refs: https://github.com/databricks/sjsonnet/pull/332

chore: Add val literal function test

---

.github/workflows/pr-build.yaml
build.sc
sjsonnet/src/sjsonnet/Format.scala
sjsonnet/test/src-js/sjsonnet/ErrorTests.scala

Per comments in https://github.com/databricks/sjsonnet/pull/305
This fixes formatting of Arr/Obj.
Also add ErrorTests to JS

Fix formatter for Array and Obj and add ErrorTests to JS

---

sjsonnet/src/sjsonnet/Parser.scala

Motivation: 
refs: https://github.com/databricks/sjsonnet/issues/331
It just fixes the MatchError, not fixed yet, feel free to take it from here.

fix: Fix parsing obj comp

---

.github/workflows/pr-build.yaml

Try ubuntu 22.04 for running actions

---

sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/src/sjsonnet/EvaluatorTests.scala

Add std.object*Ex methods

---

build.sbt
build.sc

Motivation:
Bump some dependencies' versions

chore: bump dependencies versions

---

readme.md

As the other implementations implements the std library in the host language too.

chore: Update readme for std library

---

.github/workflows/release-build.yaml

Add client/server to the build workflow

---

sjsonnet/src/sjsonnet/Format.scala
sjsonnet/test/resources/test_suite/format.jsonnet

Last part to fix the gaps found in https://github.com/databricks/sjsonnet/issues/398

Implement * in FormatSpec to dynamically insert width/precision

---

bench/src/main/scala/sjsonnet/OptimizerBenchmark.scala
bench/src/main/scala/sjsonnet/ParserBenchmark.scala
bench/src/main/scala/sjsonnet/ProfilingEvaluator.scala
bench/src/main/scala/sjsonnet/RunProfiler.scala
sjsonnet/src-jvm-native/sjsonnet/CachedResolvedFile.scala
sjsonnet/src-jvm-native/sjsonnet/OsPath.scala
sjsonnet/src/sjsonnet/BaseRenderer.scala
sjsonnet/src/sjsonnet/Error.scala
sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/src/sjsonnet/Expr.scala
sjsonnet/src/sjsonnet/ExprTransform.scala
sjsonnet/src/sjsonnet/Format.scala
sjsonnet/src/sjsonnet/Importer.scala
sjsonnet/src/sjsonnet/Interpreter.scala
sjsonnet/src/sjsonnet/Materializer.scala
sjsonnet/src/sjsonnet/Parser.scala
sjsonnet/src/sjsonnet/Renderer.scala
sjsonnet/src/sjsonnet/ScopedExprTransform.scala
sjsonnet/src/sjsonnet/Std.scala
sjsonnet/src/sjsonnet/ValScope.scala
sjsonnet/src/sjsonnet/ValVisitor.scala

Motivation:
Clean up some IDE lint problems

chore: Fix some IDE lint problems

---

sjsonnet/src-jvm-native/sjsonnet/Config.scala
sjsonnet/src-jvm-native/sjsonnet/SjsonnetMain.scala
sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/src/sjsonnet/Settings.scala
sjsonnet/src/sjsonnet/StaticOptimizer.scala
sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/src-js/sjsonnet/BaseFileTests.scala
sjsonnet/test/src-jvm-native/sjsonnet/BaseFileTests.scala
sjsonnet/test/src-jvm/sjsonnet/MainTests.scala
sjsonnet/test/src/sjsonnet/EvaluatorTests.scala
sjsonnet/test/src/sjsonnet/TestUtils.scala

Remove --no-static-error, --strict-inherited-assertions & --strict-set-operations

---

sjsonnet/src-native/sjsonnet/Platform.scala

Properly implement file hashing in scala native - using the built-in murmurhash

---

sjsonnet/src-jvm-native/sjsonnet/SjsonnetMain.scala

Fixes https://github.com/databricks/sjsonnet/issues/431

fix: Imports inside --tla-code-file,--ext-code-file.

---

sjsonnet/src/sjsonnet/Parser.scala

Motivation:
For simple cases, optimize CharsWhileIn` to `CharsWhile`

chore: tweak tripleBar parsing.

---

sjsonnet/src-jvm-native/sjsonnet/SjsonnetMainBase.scala

Before vs with this:
```
$ sjsonnet-0.5.2 -S -e '"OK"'
"OK"
$ ./out/sjsonnet/jvm/3.3.6/assembly.dest/out.jar -S -e '"OK"'
OK
```

fix: Implement --string when --multi is not set.

---

sjsonnet/src/sjsonnet/Parser.scala
sjsonnet/test/resources/go_test_suite/number_leading_zero.jsonnet.golden

Thanks to @liancheng for the fix.

Fix parsing error with numbers causing whitespaces to be consumed.

---

.scalafmt.conf
build.mill

chore: bump scala fmt to 3.9.8
