databricks/sjsonnet

sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/src/sjsonnet/Interpreter.scala
sjsonnet/src/sjsonnet/Materializer.scala
sjsonnet/src/sjsonnet/Std.scala
sjsonnet/src/sjsonnet/Val.scala
sjsonnet/test/src/sjsonnet/SjsonnetTestMain.scala

This PR lazily resolves the file path because it is only used in the `thisFile` standard library function or in error messages. Making it a lambda means that it never needs to be computed unless that function is used or an error happens.

Lazily relativize file paths

---

sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/src/sjsonnet/Interpreter.scala
sjsonnet/src/sjsonnet/SjsonnetMain.scala
sjsonnet/test/src/sjsonnet/Example.java

This PR lets clients customize import resolution ([as supported in the C library](https://github.com/google/jsonnet/blob/30f07a2684ebc40d800bb1948e1f5987e5fb02e3/include/libjsonnet.h#L67)). This is accomplished with an optional param to the evaluator that resolves a (scope, import path) to a filesystem path.
We use this to support non-filesystem paths (in particular HTTP), and it seems like the equivalent support in the C and go APIs are fairly widely used.

Add support for configuring an import callback

---

sjsonnet/src/sjsonnet/Cli.scala
sjsonnet/src/sjsonnet/Renderer.scala
sjsonnet/src/sjsonnet/SjsonnetMain.scala
sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/resources/test_suite/stdlib.jsonnet
sjsonnet/test/src/sjsonnet/YamlRendererTests.scala

Closes https://github.com/databricks/sjsonnet/issues/14 https://github.com/databricks/sjsonnet/issues/9
This pull request implements new features:
* implements `std.manifestYamlDoc` and `std.manifestYamlStream`
* `create-output-dirs`, `string`, `multi` command line options
* documents previously undocumented flags (replaces `???`)
and fixes some differences between the reference implementation and `sjsonnet`:
* `std.substr` does not care about being out of bounds - it just produces an empty output for characters out of bounds
* `std.manifestJson` does not contain spaces between `\n` characters in empty objects and arrays
* incorrect escaping of `~` has been fixed in https://github.com/google/jsonnet/pull/564
* `std.trace` outputs to stderr
NOTICE: a potentially breaking change is the …

Implement `std.manifestDocYaml` and `create-output-dirs`, `string`, `multi` command line options

---

sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/src/sjsonnet/EvaluatorTests.scala

Addresses https://github.com/databricks/sjsonnet/issues/26. Note the Jsonnet Stdlib documentation for mapWithIndex:
```
std.mapWithIndex(func, arr)
Similar to map above, but it also passes to the function the element's index in the array. The function func is expected to take the index as the first parameter and the element as the second.
```
This PR fixes function evaluation to move the index first and adds a unit test case.

fix std.mapWithIndex argument ordering

---

sjsonnet/src/sjsonnet/Parser.scala
sjsonnet/test/resources/test_suite/unicode.jsonnet

handle hex in unicode escapes

---

sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/test/src/sjsonnet/NonBooleanExprTests.scala

An expression like [x for x in [1,2,3] if 'a'] in Jsonnet results in error "Condition must be boolean, got string" - but sjsonnet does not fail. This PR fixes it.

Non-Boolean Conditions fix

---

readme.md
sjsonnet/src-js/sjsonnet/Platform.scala
sjsonnet/src-jvm/sjsonnet/Platform.scala
sjsonnet/src/sjsonnet/Std.scala

This is a modification/fix to the previous PR (Ref: https://github.com/databricks/sjsonnet/pull/48) which added a standard function to gzip the given data (String/Bytes Array) and return a Base64 encoded gzipped string back.
* We are not supporting the `gzip` feature in JS currently.
* Updated Readme file to reflect changes in the `publishArtifact` mill argument passing.
`std.gzip(...)`

Added GZip Encode Feature

---

sjsonnet/src-jvm/sjsonnet/Cli.scala
sjsonnet/src-jvm/sjsonnet/SjsonnetMain.scala

To get parity with C++/Go implementations, this commit adds support for YAML Stream Output.
Cf. https://jsonnet.org/learning/getting_started.html#stream
Closes #38

Add support for YAML Stream Output

---

build.sc
readme.md
sjsonnet/src-jvm/sjsonnet/SjsonnetMain.scala

Changes:
- Introduce `match` block to support relative as well as absolute paths for output files
- Bump Scala version to support [newer JVMs (13 & 14)](https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html)
- Bump version and clean up readme
Fixes #58.
I'm not sure how to test this and need some help adding appropriate tests :/

Add support for absolute path for output file

---

sjsonnet/src-jvm/sjsonnet/SjsonnetMain.scala
sjsonnet/src/sjsonnet/Renderer.scala
sjsonnet/test/src-jvm/sjsonnet/MainTests.scala

This prevents caching the entire output string in memory, reducing the heap usage for our largest output file of 7.2 MB from 101 MB to 93 MB in my test.
Only JSON is supported for now. YAML requires more work because the YamlRenderer is more closely tied to the underlying StringWriter, so it still has to buffer.

Write output directly to disk with -o

---

sjsonnet/src/sjsonnet/Parser.scala
sjsonnet/test/src/sjsonnet/ParserTests.scala

- The error message has a rather unhelpful position but this is consistent with the way other static errors are currently handled by Sjsonnet. The original Jsonnet parser does it better.
- There are two different places in the Jsonnet codebase where duplicate fields are detected: Statically in the parser and dynamically in the VM. It's not clear to me without digging much deeper into their C++ implementation when the second one is supposed to kick in. There is no specification or test case for the dynamic detection.
Fixes https://github.com/databricks/sjsonnet/issues/69

Detect duplicate fields in the parser

---

sjsonnet/src-jvm/sjsonnet/Cli.scala
sjsonnet/src-jvm/sjsonnet/SjsonnetMain.scala
sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/src/sjsonnet/Expr.scala
sjsonnet/src/sjsonnet/Interpreter.scala
sjsonnet/test/src/sjsonnet/EvaluatorTests.scala

This makes adjacent object literals an error. Fixes https://github.com/databricks/sjsonnet/issues/87

Add strict mode

---

build.sc
sjsonnet/src-js/sjsonnet/Platform.scala
sjsonnet/src-jvm/sjsonnet/Platform.scala
sjsonnet/src/sjsonnet/Std.scala

Added a standard function to xz the given data (String/Bytes Array) and return a Base64 encoded xz-ed string back. I ran the following commands:
```bash
./mill -i show sjsonnet[2.13.3].jvm.assembly
./mill -i show sjsonnet[2.13.3].js.fullOpt
```
* We are not supporting the `xz` feature in JS currently.
`std.xz(...)`

Added XZ Compression Support

---

.gitignore
sjsonnet/src/sjsonnet/Parser.scala
sjsonnet/test/src/sjsonnet/EvaluatorTests.scala

This PR fixes [issue 92](https://github.com/databricks/sjsonnet/issues/92) by changing the pattern match to match the '+' value to either true or false.
- A new unit test with a reproducible scenario of the issue
- `./mill "sjsonnet[2.13.3].jvm.test.testLocal"`

Fix compiler crash when '+' signal is true in a field declaration inside a list comprehension

---

sjsonnet/src/sjsonnet/Error.scala
sjsonnet/src/sjsonnet/Val.scala
sjsonnet/test/resources/imports/error.too_many_arg_with_named_arg.jsonnet
sjsonnet/test/resources/imports/single_param_function.jsonnet
sjsonnet/test/src-jvm/sjsonnet/ErrorTests.scala

This PR fixes [issue 83](https://github.com/databricks/sjsonnet/issues/83) by changing the error message thrown when two parameters are passed to a function that was expecting only one. The message now matches the official [jsonnet.org](https://jsonnet.org) specification.
- A new unit test with a reproducible scenario of the issue
- `./mill "sjsonnet[2.13.3].jvm.test.testLocal"`
- Manually tested to check the behavior when importing the function from another file

Fix error message for too many arguments with at least one named arg

---

sjsonnet/src/sjsonnet/Parser.scala
sjsonnet/test/src/sjsonnet/EvaluatorTests.scala
sjsonnet/test/src/sjsonnet/ParserTests.scala

This PR fixes [issue 99](https://github.com/databricks/sjsonnet/issues/99) by issuing an error in case an `Expr.Str` is matching with an `Expr.ForSpec` with a value greater than 1. This condition denotes that the `Expr.Str` field value would be overridden in each interaction of the `Expr.ForSpec`
- Two new unit test with a positive and negative scenario emulating the issue
- Run `./mill "sjsonnet[2.13.3].jvm.test.testLocal"` to make sure that all the tests are still passing

Do not allow duplicate field in object when evaluating list list comprehension

---

sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/resources/test_suite/stdlib.jsonnet

This fixes #103. I believe my implementation takes the same approach (in Scala) as the jsonnet implementation in https://github.com/google/jsonnet/pull/858.
Tested by running `mill __.test.test`, everything passes.

Add objectValues and objectValuesAll to stdlib

---

sjsonnet/server/src/sjsonnet/SjsonnetServerMain.scala
sjsonnet/src-jvm-native/sjsonnet/SjsonnetMain.scala
sjsonnet/src/sjsonnet/Error.scala
sjsonnet/src/sjsonnet/Interpreter.scala
sjsonnet/test/src-jvm/sjsonnet/ErrorTestsJvmOnly.scala

Catching fatal exceptions causes problems when Sjsonnet is run as a persistent worker in Bazel. When a fatal error like an OutOfMemoryError occurs, we want the process to die so it can be restarted instead of keeping a broken version around.

Only catch non-fatal exception

---

sjsonnet/src/sjsonnet/Format.scala

To improve the performance of sjsonnet's `format`, we can remove the synchronized keyword. 
History:
The synchronized keyword was added in 2018 https://github.com/databricks/sjsonnet/blob/2272e2de8b844085ff20d37807e21e5be09e7dca/sjsonnet/src/sjsonnet/Format.scala#L31. It was seemingly added to avoid potential thread issues because the `intp` variable (Python Interpreter) was not thread safe.
In the current iteration of the function, format doesn't seem to be using any global mutable objects. 
Testing: 
`./mill "sjsonnet[2.13.4].jvm.test.testLocal"` ran successfully.

remove synchronized from format string

---

sjsonnet/src-jvm-native/sjsonnet/SjsonnetMain.scala
sjsonnet/src/sjsonnet/Error.scala
sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/src/sjsonnet/Expr.scala
sjsonnet/src/sjsonnet/Importer.scala
sjsonnet/src/sjsonnet/Interpreter.scala
sjsonnet/src/sjsonnet/Materializer.scala
sjsonnet/src/sjsonnet/Parser.scala
sjsonnet/src/sjsonnet/StaticOptimizer.scala
sjsonnet/src/sjsonnet/Std.scala
sjsonnet/src/sjsonnet/Val.scala
sjsonnet/test/src-jvm-native/sjsonnet/ErrorTests.scala
sjsonnet/test/src-jvm/sjsonnet/ErrorTestsJvmOnly.scala
sjsonnet/test/src/sjsonnet/EvaluatorTests.scala

- More consistent error handling:
- Remove Error.Delegate
- Skip JVM stack trace handling
- Consistent formatting of raw delegate errors and regular positioned errors
- Unify error stack trace handling:
Instead of sprinkling error propagation with or without stack frames all over the Evaluator and other parts of the codebase, we now do it in one place (visitExpr) with additional logic in Error.withStackFrame. Duplicate frames are skipped, an error without any stack frame always gets the current position, and all other frames are added or skipped depending on the Expr at the position.
- Add expression types to stack traces:
This makes stack traces much more descriptive. We also change some of the reported positions / expr types to better match the semantics of the errors.
- Consistent …

Error handling improvements

---

bench/src/main/scala/sjsonnet/ProfilingEvaluator.scala
bench/src/main/scala/sjsonnet/RunProfiler.scala
sjsonnet/server/src/sjsonnet/SjsonnetServerMain.scala
sjsonnet/src-js/sjsonnet/SjsonnetMain.scala
sjsonnet/src-jvm-native/sjsonnet/Config.scala
sjsonnet/src-jvm-native/sjsonnet/SjsonnetMain.scala
sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/src/sjsonnet/Interpreter.scala
sjsonnet/src/sjsonnet/Materializer.scala
sjsonnet/src/sjsonnet/Settings.scala
sjsonnet/src/sjsonnet/StaticOptimizer.scala
sjsonnet/src/sjsonnet/Std.scala
sjsonnet/src/sjsonnet/Val.scala
sjsonnet/test/resources/db/unused_illegal_var.jsonnet
sjsonnet/test/src-jvm-native/sjsonnet/ErrorTests.scala
sjsonnet/test/src-jvm-native/sjsonnet/MainTests.scala
sjsonnet/test/src/sjsonnet/FormatTests.scala
sjsonnet/test/src/sjsonnet/TestUtils.scala

Warnings could prove useful in the long run if we want to add linting. `--no-static-errors` is provided for migrating from the previous version but should be removed again in the long term because the specification requires static error handling. Since warnings are not thrown they do not get a full stack trace. Only the actual position of the warning is reported.

Add support for warnings and --no-static-errors

---

sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/test/src-jvm-native/sjsonnet/ErrorTests.scala
sjsonnet/test/src/sjsonnet/EvaluatorTests.scala

`a[a.length]` was not detected correctly, leading to an internal error instead of the expected error message

Fix upper array bounds handling

---

bench/src/main/scala/sjsonnet/MainBenchmark.scala
bench/src/main/scala/sjsonnet/MultiThreadedBenchmark.scala
sjsonnet/src/sjsonnet/Val.scala

Static Val.Obj instances are created by the optimizer and will end up in the parse cache. If the cache is shared by multiple threads, initialization must be sufficiently safe, i.e. computing a value multiple times in race conditions is allowed (and cheaper than ensuring that it doesn't happen), but object must never get into an invalid intermediate state.

Make lazy initialization of static Val.Obj thread-safe

---

sjsonnet/src/sjsonnet/Parser.scala

This leads to slower results in ParseBenchmark (~ 5%) but with parsing taking only 10% of the total time in the main benchmark, the potential for performance regressions is severely limited. We see an improvement of overall benchmark times, both single-threaded and multi-threaded with a shared parse cache, in the main benchmark.

Deduplicate strings in the parser

---

readme.md

Update the SjsonnetMain.interpret's signature for the readme.md JS example
Related to #54

readme:  Update the JS example

---

sjsonnet/src/sjsonnet/Format.scala
sjsonnet/src/sjsonnet/Val.scala
sjsonnet/test/resources/db/error.format_func.jsonnet
sjsonnet/test/src-jvm-native/sjsonnet/ErrorTests.scala

For compatibility with jsonnet. Fixes #144.

Disallow function values in std.format

---

sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/test/src/sjsonnet/EvaluatorTests.scala

Fixes #121 
Please advise on checking for size twice vs calling `contains` once per key, I haven't benchmarked this.
This might also break some existing files which rely on this behavior without realizing it's out of spec, either with duplicate list entries getting reduced or more complex replacements where only the last entry matters. Not sure if we're ok with that or  what other options we have. Breaking these probably beats allowing duplicate entries in the future.

[ES-449270] Fix duplicate key error in object comprehension

---

sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/test/src/sjsonnet/EvaluatorTests.scala

These are meant to get materialized, similar to `error` which we already handle correctly.
Added a unit test.
Fixes https://github.com/databricks/sjsonnet/issues/146

Allow assertions to take non-string error messages

---

sjsonnet/src/sjsonnet/Parser.scala
sjsonnet/test/src/sjsonnet/EvaluatorTests.scala

Fixes https://github.com/databricks/sjsonnet/issues/152 and https://github.com/databricks/sjsonnet/issues/65. All the other places we parse keywords are followed by a `~~ break` to ensure the keyword ends there, so `"assert"` should as well. 
Added some tests to loop through all the keywords to make sure this behavior doesn't appear for any of the other ones, in the three distinct contexts I can think of where identifiers might appear (local variable declarations, expressions, and object keys)

Fix parsing of object key starting with `assert`

---

bench/src/main/scala/sjsonnet/MainBenchmark.scala
bench/src/main/scala/sjsonnet/MaterializerBenchmark.scala
bench/src/main/scala/sjsonnet/ProfilingEvaluator.scala
bench/src/main/scala/sjsonnet/RunProfiler.scala
sjsonnet/src-js/sjsonnet/SjsonnetMain.scala
sjsonnet/src-jvm-native/sjsonnet/SjsonnetMain.scala
sjsonnet/src/sjsonnet/Error.scala
sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/src/sjsonnet/Interpreter.scala
sjsonnet/src/sjsonnet/Std.scala
sjsonnet/src/sjsonnet/Util.scala
sjsonnet/src/sjsonnet/Val.scala
sjsonnet/test/src-jvm-native/sjsonnet/FileTests.scala
sjsonnet/test/src/sjsonnet/FormatTests.scala
sjsonnet/test/src/sjsonnet/Std0150FunctionsTests.scala

Fixes https://github.com/databricks/sjsonnet/issues/110 and https://github.com/databricks/sjsonnet/issues/149 and https://github.com/databricks/sjsonnet/issues/74 and https://github.com/databricks/sjsonnet/issues/56 and https://github.com/databricks/sjsonnet/issues/47 and https://github.com/databricks/sjsonnet/issues/114 and https://github.com/databricks/sjsonnet/issues/76
Mostly straightforward changes, though the constructor signature of `Interpeter` and `Evaluator` had to change a bit to satisfy the fixed `extCode` semantics. Added unit tests to assert the correct behaviors

Std lib improvements: add std.slice and std.manifestJsonMinified, fix handling of numbers in manifestXmlJsonml, handling of code in extCode

---

sjsonnet/src/sjsonnet/Val.scala
sjsonnet/test/src/sjsonnet/EvaluatorTests.scala
sjsonnet/test/src/sjsonnet/PreserveOrderTests.scala
sjsonnet/test/src/sjsonnet/StdFlatMapTests.scala
sjsonnet/test/src/sjsonnet/TestUtils.scala

Fixes https://github.com/databricks/sjsonnet/issues/21

Properly propagate object assertions during inheritance

---

sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/src/sjsonnet/Std0150FunctionsTests.scala

Fixes https://github.com/databricks/sjsonnet/issues/108. This is not documented behavior, but we should try and be compatible anyway

Allow std.fold{l,r} to take strings

---

build.sbt
build.sc
sjsonnet/src-js/sjsonnet/Platform.scala
sjsonnet/src-jvm/sjsonnet/Platform.scala
sjsonnet/src-native/sjsonnet/Platform.scala
sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/src-jvm/sjsonnet/ParseYamlTests.scala

This PR adds a new `parseYaml()` function to **sjsonnet**.
[JSONNET Reference Doc](https://jsonnet.org/ref/stdlib.html#:~:text=yields%20%7B%20%22foo%22%3A%20%22bar%22%20%7D.-,std.parseYaml(str),-Available%20since%20version)
---
**Signed-off-by:** Rohit Agrawal <rohit.agrawal@databricks.com>

*New* Add parseYaml() Function

---

.gitignore
build.sbt
project/build.properties

The ancient version 1.3.10 doesn't fully support Mac ARM architectures

Upgrade to latest sbt 1.9.4

---

bench/src/main/scala/sjsonnet/MainBenchmark.scala
bench/src/main/scala/sjsonnet/OptimizerBenchmark.scala
bench/src/main/scala/sjsonnet/ParserBenchmark.scala
readme.md
sjsonnet/src/sjsonnet/Importer.scala
sjsonnet/src/sjsonnet/Interpreter.scala
sjsonnet/src/sjsonnet/Parser.scala
sjsonnet/src/sjsonnet/StaticOptimizer.scala
sjsonnet/src/sjsonnet/Val.scala
sjsonnet/test/src/sjsonnet/ParserTests.scala

- This PR uses the Parser & StaticOptimizer thread local string interner for keys in static objects
- Similarly, we deduplicate the String -> Boolean map used to determine if a field is static.
- For static objects we also use immutable.VectorMap (with a JavaWrapper) for the field set.
- Lastly for the value cache, we size it according to the number of keys in the object this reduces unnecessary up-sizing for large objects, and more importantly removes the large number of sparse maps we previously had for small objects (the default was 16 elements)
Before: 855MB for the parsed file
After: 425MB

Static Object Optimizations

---

build.sbt
build.sc
sjsonnet/src-js/sjsonnet/Platform.scala
sjsonnet/src-jvm-native/sjsonnet/CachedResolvedFile.scala
sjsonnet/src-jvm/sjsonnet/Platform.scala
sjsonnet/src-native/sjsonnet/Platform.scala
sjsonnet/src/sjsonnet/Importer.scala
sjsonnet/test/src-jvm/sjsonnet/XxHash64Tests.scala

- CRC32 collision probability is too high for comfort since it's only 32-bits
- Switching to XXHash64 since its a high quality hash, 64-bits and extremely fast (faster than CRC32
for medium size inputs: https://lz4.github.io/lz4-java/1.3.0/xxhash-benchmark/)

Switch Content Hashing from CRC32 to XXHash64

---

sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/src/sjsonnet/Std0150FunctionsTests.scala

This implements the std.get function in sjsonnet.

implement std.get function

---

readme.md
sjsonnet/src-js/sjsonnet/Platform.scala
sjsonnet/src-jvm/sjsonnet/Platform.scala
sjsonnet/src-native/sjsonnet/Platform.scala
sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/src-jvm/sjsonnet/StdShasTests.scala
sjsonnet/test/src/sjsonnet/Std0150FunctionsTests.scala

This PR adds a bunch of missing methods to sjsonnet.
- isEmpty
- xor
- xnor
- trim
- equalsIgnoreCase
- sha1
- sha256
- sha512
- sha3

Add a few more methods to sjsonnet, like std.sha*, std.trim, std.isEmpty

---

sjsonnet/src-jvm-native/sjsonnet/SjsonnetMain.scala
sjsonnet/src/sjsonnet/Interpreter.scala

this fixes --exec, --tla-str and --ext-str on windows as < and > are illegal file name characters.
fixes #200

fix: Use different chars for synthetic paths.

---

sjsonnet/src/sjsonnet/Renderer.scala
sjsonnet/test/src/sjsonnet/Std0150FunctionsTests.scala

Problem: std.manifestJsonMinified was producing newlines in empty arrays or empty objects:
```
$ jsonnet -e 'std.manifestJsonMinified({a:[],b:{}})'
"{\"a\":[],\"b\":{}}"
$ sjsonnet-0.4.10 -e 'std.manifestJsonMinified({a:[],b:{}})'
"{\"a\":[\n],\"b\":{\n}}"
```
Fix that and update the tests too.

fix: std.manifestJsonMinified and empty arrays/objects.

---

project/build.properties
sjsonnet/src/sjsonnet/Expr.scala

Motivation:
`then` is a keyword in Scala 3 now.

chore: Rename then to `then` in IfElse expr

---

sjsonnet/src/sjsonnet/Std.scala
sjsonnet/src/sjsonnet/Val.scala
sjsonnet/test/src/sjsonnet/StdWithKeyFTests.scala

Fixes #204, by really calling keyF for all types in the array.

Fix sorting algorithm to work for all array types

---

readme.md
sjsonnet/src/sjsonnet/Format.scala
sjsonnet/test/src/sjsonnet/FormatTests.scala

Add a check to make sure the format array is of the right size and type
- fix https://github.com/databricks/sjsonnet/issues/139
- fix https://github.com/databricks/sjsonnet/issues/185

Add better error handling for format

---

.github/workflows/pr-build.yaml
sjsonnet/src-jvm-native/sjsonnet/SjsonnetMain.scala
sjsonnet/src/sjsonnet/Interpreter.scala
sjsonnet/src/sjsonnet/Util.scala
sjsonnet/test/src-jvm/sjsonnet/BufferedRandomAccessFileTests.scala

This PR fixes a regression introduced by https://github.com/databricks/sjsonnet/issues/208
That PR aimed to fix https://github.com/databricks/sjsonnet/issues/200, an issue where `std.extVar` failed on Windows because it tried to resolve mock paths which contained `<` and `>` characters which are forbidden in Windows filenames.
That PR's solution was to use Unicode less-than and greater-than characters in place of ASCII `<` and `>`, but that broke things for Unix/Linux platforms with a non-UTF8 `LANG` (see https://github.com/databricks/sjsonnet/pull/208#pullrequestreview-2452961190).
In this PR, I aim to fix this by flagging the other PR's change to only occur for Windows, while continuing to use ASCII `<` and `>` as before on other platforms.
I also added a regression test by pinning …

Flag use of Unicode less-than and greater-than characters in FilePath to be a Windows-only change

---

sjsonnet/src/sjsonnet/Val.scala

This PR fixes a thread-safety bug in Val.obj.getAllKeys, similar to the previous fix in https://github.com/databricks/sjsonnet/pull/136. It looks like this particular site was overlooked in that earlier PR.
I spotted this potential issue while reading through the code, not via actual use.

Fix thread-safety bug in Obj.getAllKeys

---

build.sbt
build.sc
readme.md
sjsonnet/src-jvm/sjsonnet/Platform.scala
sjsonnet/test/src-jvm/sjsonnet/StdGzipTests.scala
sjsonnet/test/src-jvm/sjsonnet/StdXzTests.scala

The output of std.gzip and std.xz was truncated because the output stream was closed after being read and encoded into base64.
This regression was introduced in https://github.com/databricks/sjsonnet/pull/210

Fix a bug leading to the truncation of the data returned by std.gzip and std.xz

---

sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/src/sjsonnet/Materializer.scala
sjsonnet/src/sjsonnet/Val.scala

This PR implements a memory usage optimization related to `Lazy`: once we have evaluated a Lazy value, we no longer need to retain the closure that performed the evaluation. Discarding closures (and, transitively, their dependencies) after lazy evaluation saves memory.
We have a single jsonnet file which has very high peak memory requirements during evaluation. I captured a heap dump and noticed significant memory usage due to `sjsonnet.Lazy[]`, with over half the shallow size consumed by `Lazy[]` arrays:
From the merged paths view, we see that most of these are retained from anonymous classes:
For example, here `sjsonnet.Evaluator$$anonfun$visitAsLazy$2` corresponds to the `() => visitExpr(e)` in https://github.com/databricks/sjsonnet/blob/759cea713bc8e39f45b844a75358fd780f75d480/sjsonnet …

Memory usage optimization: discard compute closure after evaluation in Lazy

---

sjsonnet/src/sjsonnet/Std.scala

This PR implements small performance optimizations for two built-in functions:
- **std.findSubstr**:
- Skip array allocation in case of no matches. This is a common scenario because `findSubstr` is often used to implement "string contains" checks.
- Use `ArrayBuilder` instead of `ArrayBuffer`: in this context we only need to append and don't need to update, remove, or inspect the elements that we've written, and for those requirements ArrayBuilder is cheaper to instantiate and cheaper to invoke.
- Store `Val.Num` into the array builder rather than storing indices then mapping the result into an output array: this saves an array allocation and iteration.
- **std.flattenArrays**:
- Apply a similar ArrayBuffer -> ArrayBuilder replacement.

Optimize std.findSubstr and std.flattenArrays

---

bench/src/main/scala/sjsonnet/ProfilingEvaluator.scala
sjsonnet/src/sjsonnet/Expr.scala
sjsonnet/src/sjsonnet/Format.scala
sjsonnet/src/sjsonnet/Std.scala
sjsonnet/src/sjsonnet/Val.scala
sjsonnet/test/src-jvm-native/sjsonnet/ErrorTests.scala

This PR does 2 things:
It improves std.get() to only compute default when it's needed.
and it makes builtin error more readable
Before
```
bazel-bin/bazel/jsonnet/sjsonnet.jar -e 'std.get(["a", "b"], "a", null)'
sjsonnet.Error: Wrong parameter type: expected Object, got array
at [ApplyBuiltin].(<exec>:1:8)
```
after
```
bazel-bin/bazel/jsonnet/sjsonnet.jar -e 'std.get(["a", "b"], "a", null)'
sjsonnet.Error: Wrong parameter type: expected Object, got array
at [std.get].(<exec>:1:8)
````

Improve std.get and error messages

---

sjsonnet/src/sjsonnet/Interpreter.scala
sjsonnet/src/sjsonnet/Materializer.scala
sjsonnet/test/src/sjsonnet/EvaluatorTests.scala

This is inline with go-jsonnet's behavior.
This behavior difference made TLA vars working properly in sjsonnet - I moved this part to the interpreter.
This fixes #168

Stop manifesting functions with no arguments in objects by default

---

sjsonnet/src/sjsonnet/Expr.scala
sjsonnet/src/sjsonnet/Parser.scala
sjsonnet/test/src/sjsonnet/ParserTests.scala

Fix "Duplicate Local Variables in Object Scope"

---

sjsonnet/src/sjsonnet/Std.scala

This PR optimizes `lstripChars` / `rstripChars` / `stripChars` built-in functions by using the specialization framework from #119 / 0bd255a7486f4889b06581afeac8058548995cf3 to pre-compile and re-use `Pattern` instances when the replacement / strip arguments are constants.
In Java, `String.replaceAll()` compiles and uses a `Pattern` under the hood and this is relatively expensive; specialization lets us save this cost when the `chars`-to-be-stripped are constant.
**Correctness**: ran all tests with a manual change to disable static function application optimizations (a prerequisite required to achieve full test coverage, as the static application prevents specialization from kicking in during most tests). In a followup, I think we should explore adding flags for optimizer features and …

Optimize lstripChars, rstripChars, and stripChars via specialization

---

sjsonnet/src/sjsonnet/Std.scala

This PR fixes a performance regression from #227 / 4c85bde425b51103a95efce272fa0e4fb1bd51dd which I overlooked in review:
When generalizing the optimized non-Pattern-based split code, that commit introduced a `.substring()` on each character, producing tons of garbage.
Instead, I think we can do a `.startsWith(splitPattern, i)`: this should be much faster because it will avoid unnecessary garbage string creation (plus I'm pretty sure that `startsWith` is optimized in modern JDKs).
I also removed the use of `breakable` and replaced it with an update to the `while` condition.

Fix performance regression in split by avoiding allocating substring per char

---

sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/src/sjsonnet/StdWithKeyFTests.scala

Relax setUnion strictness towards arguments: basically std.set() and std.setUnion will be able to create a set.
Fix the bad bug where one of the argument was empty - we just returned the empty set instead of the other one.

Fix a bug in the strict implementation of setUnion

---

build.sc

Motivation:
When compiles it on JDK21, it needs newer version of Scala
Result:
compiles with Java 21 successfully
refs: https://github.com/databricks/sjsonnet/issues/228

chore: bump scala to make it compiles on Java 21

---

sjsonnet/src-native/sjsonnet/Platform.scala
sjsonnet/src/sjsonnet/ReadWriter.scala
sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/src-jvm-native/ErrorTests.scala
sjsonnet/test/src-jvm/sjsonnet/Example.java
sjsonnet/test/src-jvm/sjsonnet/StdGzipTests.scala
sjsonnet/test/src-jvm/sjsonnet/StdXzTests.scala
sjsonnet/test/src-native/sjsonnet/StdGzipTests.scala

- Add support std.native
- Move our non-standard std.xz/std.gzip to this.
- Add gzip support to scala native.

Add std.native & move std.xz/gzip to this

---

sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/src/sjsonnet/StdWithKeyFTests.scala

This PR improves the performance of `std.sort` and related functions when `keyF` is used.
The existing implementation evaluates `keyF` multiple times per input element because:
- Prior to sorting, it evaluates `keyF` on all elements to check whether all keys are of the same type.
- During sorting, it re-evaluates `keyF` on every pair of compared elements.
In the best case (an already-sorted array), this performs ~3x more evaluations than needed because each element participates in up to two extra unnecessary comparisons. In the worst case, we have to do additional comparisons during sorting and the unnecessary work will be even higher.
The fix:
- Precompute all keys up front (which we already do for type-checking purposes).
- Sort an array of indices using a comparator which fetches their …

Optimization: std.sort should only evaluate keyF once per array element

---

sjsonnet/src-jvm/sjsonnet/Platform.scala
sjsonnet/src/sjsonnet/Materializer.scala
sjsonnet/test/src-jvm/sjsonnet/ParseYamlTests.scala

I was looking at https://github.com/google/jsonnet/issues/1109 and realized that we did not parse yaml correctly for primitive types:
`std.parseYaml("0777")` returned `[511]` instead of `511` (something that other implementations of jsonnet do)

Fix corner case for YAML parsing with primitive types

---

build.sbt
build.sc
sjsonnet/src-js/sjsonnet/Platform.scala
sjsonnet/src-jvm/sjsonnet/Platform.scala
sjsonnet/src-native/sjsonnet/Platform.scala
sjsonnet/src/sjsonnet/PrettyYamlRenderer.scala
sjsonnet/src/sjsonnet/Std.scala
sjsonnet/src/sjsonnet/StdRegex.scala
sjsonnet/src/sjsonnet/TomlRenderer.scala
sjsonnet/src/sjsonnet/YamlRenderer.scala
sjsonnet/test/src/sjsonnet/OldYamlRenderer.scala
sjsonnet/test/src/sjsonnet/StdRegexTests.scala

With this PR, I'm adding a handful of methods to expose regular expressions in jsonnet, through std.native()
I'm modeling them after [this open PR from jsonnet](https://github.com/google/jsonnet/pull/1039), which was ported to jrsonnet.
For now, they are in std.native() as they are not part of the default std package and use RE2 instead of the native regexp package (for performance and compatibility reasons with a future go-jsonnet implementation).
- regexFullMatch(pattern, str) -- Full match regex
- regexPartialMatch(pattern, str) -- Partial match regex
- regexReplace(str, pattern, to) -- Replace single occurance using regex
- regexGlobalReplace(str, pattern, to) -- Replace globally using regex
and the utility function:
- regexQuoteMeta(str) -- Escape regex metachararacters
Those …

Add RegEx supports using RE2 to sjsonnet

---

sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/src/sjsonnet/StdMergePatchTests.scala

This PR fixes a bug related to handling of hidden fields in `std.mergePatch`:
In both google/jsonnet and google/go-jsonnet, hidden fields are ineligible to participate in field merges:
- `std.mergePatch({a: 1}, {a :: 2}`
- should return `{a: 1}` (ignoring the hidden patch field)
- sjsonnet returns `{a: 2}`
- `std.mergePatch({a: {a: 1}}, {a:: {b: 1}}`
- should return `{a: {a: 1}}`
- sjsonnet returns `{a: {a: 1, b: 1}}`
- `std.mergePatch({a:: {a: 1}}, {a: {b: 1}}` (symmetrical to previous case, but swaps hidden between target and patch)
- should return `{a: {b: 1}}`
- sjsonnet returns `{a: {a: 1, b: 1}}`
The problem is that the current code iterates over the union of visible fields, but never re-checks the specific visibility in target and patch during per-field merges.
This PR fixes that …

Fix a bug in hidden field handling in std.mergePatch

---

sjsonnet/src-native/sjsonnet/Platform.scala
sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/src/sjsonnet/StdStripCharsTests.scala

With this PR, I fix a regression introduced with the migration to RE2.
- If there's a - in the chars in the *stripchars functions, we move it to the end
- explicitely use RE2 with scala native (instead of the thin wrapper around it), which then allows us to
- Enable stripchars test cases for jvm, js & native.

Fix usage of - in stripChars with the introduction of RE2

---

sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/src/sjsonnet/StdMergePatchTests.scala

This PR changes the default visibility of fields in objects created by `std.mergePatch`: previously they were at `Unhide` visibility, equivalent to the `:::` operator, but as of this PR they are now at `Normal` standard visibility.
Concretely, previously 
```sjsonnet
{a:: 0} + std.mergePatch({a: 1}, {})
```
would return `{a: 1}` but after this patch it returns `{a:: 1)`, i.e. it preserves the hidden field.
It turns out that v0.20.0 of google/jsonnet and google/go-jsonnet also differ in their behavior here. That, in turn, is due to a behavior difference in the default visibility of fields in object comprehension results: jsonnet marks object comprehension fields as forced-visible, while go-jsonnet marks them as inherited visibility; see https://github.com/google/jsonnet/issues/1111. …

std.mergePatch should create resulting object fields at Normal visibility, not Unhide

---

sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/src/sjsonnet/Expr.scala
sjsonnet/src/sjsonnet/Std.scala
sjsonnet/src/sjsonnet/Util.scala
sjsonnet/src/sjsonnet/Val.scala
sjsonnet/src/sjsonnet/ValVisitor.scala

This PR bundles together several small optimizations, most aimed at reducing garbage object creation. Collectively, these changes result in a large performance improvement for some of our largest jsonnet inputs.
These are somewhat coherently split into multiple smaller intermediate commits, which can help for navigating this change. I'll describe each optimization in more detail below.
The `hasKeys`, `containsKey`, `containsVisibleKey`, `allKeyNames`, and `visibleKeyNames` methods can be optimized in the common case of objects that don't have `super` objects. 
We already perform an optimization for `static` objects, pre-populating `allKeys`, but for non-static objects we had to run `gatherAllKeys` to populate a `LinkedHashMap` of keys and a boolean indicating visibility.
If a non-static …

Several performance optimizations, primarily aimed at reducing garbage object creation in common cases

---

build.sbt
build.sc
sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/src/sjsonnet/Expr.scala
sjsonnet/src/sjsonnet/ExprTransform.scala
sjsonnet/src/sjsonnet/Interpreter.scala
sjsonnet/src/sjsonnet/Parser.scala
sjsonnet/src/sjsonnet/StaticOptimizer.scala
sjsonnet/src/sjsonnet/Std.scala
sjsonnet/src/sjsonnet/Val.scala
sjsonnet/test/resources/test_suite/recursive_function_native.jsonnet
sjsonnet/test/src-jvm/sjsonnet/FileTests.scala
sjsonnet/test/src-native/sjsonnet/FileTests.scala
sjsonnet/test/src/sjsonnet/FormatTests.scala

With this PR, I'm implementing tailstrict in sjsonnet.
I'm following the guidance from https://github.com/google/jsonnet/issues/343#issuecomment-325987638:
Quote:
1. If you call a function with tailstrict annotation on the apply AST, e.g. foo(42) tailstrict then the evaluation of the function body happens in "tail strict mode". The annotated AST need not actually be a tail call. Also, the arguments of this function are forced.
2. When another function call (can be a completely different function to the one that was originally called) is made when we're evaluating in "tail strict mode" and it is a tail call, then the current stack frame is re-used for the next call, rather than being pushed on top of.
3. Note that in order to preserve the tail strict mode into the new function, the new …

Add support for tailstrict

---

build.sc
sjsonnet/src-js/sjsonnet/SjsonnetMain.scala
sjsonnet/src-jvm-native/sjsonnet/CachedResolvedFile.scala
sjsonnet/src/sjsonnet/Importer.scala
sjsonnet/test/resources/test_suite/regex_js.jsonnet
sjsonnet/test/resources/test_suite/stdlib_native.jsonnet
sjsonnet/test/src-js/sjsonnet/FileTests.scala
sjsonnet/test/src-native/sjsonnet/FileTests.scala

For completeness, adding FileTests to JS.
It required a bit of custom source generation to bundle all the resources in the JS, but it works.
Found an issue with importbin in JS, fixed it.

Add FileTests to JS

---

sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/src/sjsonnet/Expr.scala
sjsonnet/src/sjsonnet/ExprTransform.scala
sjsonnet/src/sjsonnet/Format.scala
sjsonnet/src/sjsonnet/StaticOptimizer.scala
sjsonnet/src/sjsonnet/Std.scala
sjsonnet/src/sjsonnet/StdRegex.scala
sjsonnet/src/sjsonnet/Val.scala
sjsonnet/test/src/sjsonnet/Std0150FunctionsTests.scala

Basically, 
```
std.get({a: 1}, "a", default=error "a")
```
should not execute default unless needed.
In the current implementation, builtins evaluates all arguments by default. This change changes that. Now Builtins have to force arguments when they need it.

Make std.get handle default lazily

---

sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/resources/test_suite/stdlib.jsonnet
sjsonnet/test/resources/test_suite/stdlib_native.jsonnet

Adds to the std object some functions:
- trigonometric: std.atan2, std.hypot, std.deg2rad, std.rad2deg
- logarithmic: std.log2, std.log10
And one constant: std.pi

Add new math functions to keep up with go-jsonnet

---

sjsonnet/src-jvm-native/sjsonnet/SjsonnetMain.scala
sjsonnet/src/sjsonnet/Interpreter.scala

Motivation:
Currently, I'm using sjsonnet from Java, which will require me to convert to Scala's immutable map.
Modification:
Instead of converting, add a query function to look up the value.
Result:
Less overhead when using in Java

chore: support query extVar and tlaVar with a function.

---

sjsonnet/src/sjsonnet/Interpreter.scala

Motivation:
fix: https://github.com/databricks/sjsonnet/issues/279
Otherwise, if a static parse cache is used, then the same extVar/tlaVar with a different value will be cached.
Modification:
Separate the `varParseCache`

chore: Avoid using the same parse cache for both jsonnet and variables

---

sjsonnet/src/sjsonnet/Val.scala

Otherwise people can't extend `sjsonnet.Val.Builtin2` since they can't implement
```
def evalRhs(
arg1: sjsonnet.Lazy,
arg2: sjsonnet.Lazy,
ev: sjsonnet.EvalScope,
pos: sjsonnet.Position): sjsonnet.Val = {
```
See [example](https://github.com/databricks-eng/universe/pull/1015923)

Make lazy not a protected class

---

sjsonnet/src/sjsonnet/Error.scala
sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/src/sjsonnet/StaticOptimizer.scala
sjsonnet/src/sjsonnet/Val.scala

Motivation:
Add some static optimization for long run jsonnet script.

chore: add some static optimization

---

sjsonnet/src/sjsonnet/FunctionBuilder.scala
sjsonnet/src/sjsonnet/Std.scala

Motivation:
Make the `buildin`* helper function accessible without extending the `Std()` class.
Then I can just extend the `FunctionBuilder`, build the `additionalNativeFunctions`, and then pass it to the `Std()`'s constructor.
otherwise: 
```scala
object JsonnetStdExt extends Std(Map.empty) {
val extFunctions: Map[String, Val.Func] = Map(
builtin("objectReplaceKey", "obj", "key", "newKey") {
(pos, ev, o: Val.Obj, key: String, newKey: String) =>
val bindings: Array[(String, Val.Obj.Member)] = for {
k <- o.visibleKeyNames
v = o.value(k, pos.fileScope.noOffsetPos)(ev)
} yield {
val newKeyName = if (k == key) newKey else k
(newKeyName, new Val.Obj.ConstMember(false, Visibility.Normal, v))
}
Val.Obj.mk(pos, bindings)
}
)
}
```

chore: Extract buildin* to FunctionBuilder

---

sjsonnet/src/sjsonnet/Std.scala

It should be a `Val.Func` to make it works well with `buildin` functions.
otherwise:
```scala
new Std(JsonnetStdExt.extFunctions.asInstanceOf[Map[String, Val.Builtin]]).Std
```

chore: Change the additionalNativeFunctions to accept Val.Func

---

sjsonnet/src/sjsonnet/Std.scala

Motivation:
Support registry addtional `std`* functions, other than `std.native('xxxfunction')(...)`
eg:
```jsonnet
local input = {
"person1": {
"name": "Alice",
"welcome": "Hello Alice!"
},
"person2": {
"name": "Bob",
"welcome": "Hello Bob!"
}
};
{
// Extracting the name of person1 using JSONPath
extractedName: std.jsonpath(input, "$.person1.name")[0],
// Extracting the welcome message of person2 using JSONPath
extractedWelcome: std.jsonpath(input, "$.person2.welcome")[0],
}
```

chore: Add additional std function support.

---

sjsonnet/src-jvm-native/sjsonnet/SjsonnetMain.scala
sjsonnet/src/sjsonnet/ExternalVariable.scala
sjsonnet/src/sjsonnet/ExternalVariableKind.scala
sjsonnet/src/sjsonnet/Interpreter.scala

Motivation:
When using Java, I query a Java hashmap, I can then emit the `Expr` directly, instead of converting it to a string and then parsing it.

chore: Add `evaluateVar` to interpreter.

---

sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/src/sjsonnet/Expr.scala
sjsonnet/src/sjsonnet/Val.scala

Motivation:
As we are running sjsonnet in a long running app, change the long visitExpr with a  table switch will make it faster.

feat: make it evaluate a tableswitch.

---

sjsonnet/src/sjsonnet/Std.scala

Not a big deal, but refs: https://github.com/google/jsonnet/pull/1212

chore: rename std.substr's parameter name from `s` to `str`

---

sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/src/sjsonnet/StdMergePatchTests.scala

This PR fixes #307, an issue where sjsonnet's `std.mergePatch` is overly eager in its evaluation of target object fields in certain circumstances.
```jsonnet
(std.mergePatch({ boom: error "should not error" }, {}) + { flag: 42 }).flag
```
and
```jsonnet
(std.mergePatch({ boom: error "should not error" }, { boom: null }) + { flag: 42 }).flag
```
and
```jsonnet
(std.mergePatch({ boom: error "should error" }, { boom: 1 }) + { flag: 42 }).flag
```
all print `42` in both google/jsonnet and go-jsonnet. In all cases, the target object contains a field, `boom`, which throws an error if evaluated. 
In the first case, the `boom` field doesn't merge with any patch field and isn't required in the final output materialization and thus should not be evaluated.
In the second case, the `boom `field is …

Fix overly-eager evaluation of unmerged or removed target fields in std.mergePatch

---

bench/src/main/scala/sjsonnet/OptimizerBenchmark.scala
sjsonnet/src-jvm-native/sjsonnet/SjsonnetMain.scala
sjsonnet/src/sjsonnet/Interpreter.scala
sjsonnet/src/sjsonnet/StaticOptimizer.scala
sjsonnet/test/src/sjsonnet/ExtFunctionNamespaceTest.scala

Motivation:
Instead of adding methods to `std`, adding them to a separate namespace seems better and safer.
```jsonnet
local input = {
"name": "Alice",
"welcome": "Hello Alice!"
};
tb.objectReplaceKey(input,"name", "newName")
```
Here we bind the `objectReplaceKey` function to `tb`, and then get the right result.
```json
{"newName":"Alice","welcome":"Hello Alice!"}
```

feat: Add variableResolver to separate the namespaces.

---

sjsonnet/src/sjsonnet/ReadWriter.scala

Motivation:
Add ReadWriter instance for Val.Literal, we need this when returns a `Val.Literal` from function.

feat: Add ReadWriter instance for Val.Literal

---

sjsonnet/src/sjsonnet/Std.scala
sjsonnet/src/sjsonnet/Val.scala
sjsonnet/src/sjsonnet/functions/AbstractFunctionModule.scala
sjsonnet/src/sjsonnet/functions/FunctionBuilder.scala
sjsonnet/src/sjsonnet/functions/FunctionModule.scala
sjsonnet/test/src/sjsonnet/ExtFunction0Test.scala
sjsonnet/test/src/sjsonnet/ExtFunctionNamespaceTest.scala
sjsonnet/test/src/sjsonnet/ValLiteralFunctionTest.scala

Motivation:
Provide some helper classes.
our current use cases:
```scala
object FunctionRegistry extends FunctionModule {
override final val name: String = "tb"
override final lazy val module: Val.Obj = moduleFromModules(
URLFunctions,
ObjectFunctions,
JsonPathFunctions)
}
```

feat: Add FunctionModule helper classes.

---

sjsonnet/src/sjsonnet/Evaluator.scala

Motivation:
Add missing case in https://github.com/databricks/sjsonnet/pull/338
Otherwise it will fails to a MatchError, where it has a parameter type mismatch error message. 
The current spec will not do any implicit conversion anyway.

chore: Fix matching warning when visit slice.

---

sjsonnet/src/sjsonnet/StaticOptimizer.scala
sjsonnet/src/sjsonnet/Val.scala

This partially reverts commit 60db9d0256b042ce70dc4eb1c50d269ed53fd771.
This is causing performance regressions

Revert "chore: add some static optimization (#294)"

---

sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/src/sjsonnet/Interpreter.scala
sjsonnet/src/sjsonnet/Settings.scala
sjsonnet/test/src/sjsonnet/EvaluatorTests.scala
sjsonnet/test/src/sjsonnet/TestUtils.scala

Before:
```
Result "com.databricks.jsonnet.bundle.test.InternalJsonnetBuilderBenchmark.main":
239.623 ±(99.9%) 2.487 ms/op [Average]
(min, avg, max) = (238.165, 239.623, 242.976), stdev = 1.645
CI (99.9%): [237.136, 242.110] (assumes normal distribution)
```
After:
```
Result "com.databricks.jsonnet.bundle.test.InternalJsonnetBuilderBenchmark.main":
224.443 ±(99.9%) 1.335 ms/op [Average]
(min, avg, max) = (223.504, 224.443, 226.269), stdev = 0.883
CI (99.9%): [223.108, 225.779] (assumes normal distribution)
```
Looks like there's still a small regression somewhere - will continue investigating
Initial 3.3.5 commit
```
Result "com.databricks.jsonnet.bundle.test.InternalJsonnetBuilderBenchmark.main":
216.718 ±(99.9%) 2.125 ms/op [Average]
(min, avg, max) = (214.841, 216.718, 218.835), stdev …
```

Restore old Evaluator switch, and put the new Evaluator behind a flag

---

sjsonnet/src/sjsonnet/Interpreter.scala
sjsonnet/src/sjsonnet/StaticOptimizer.scala
sjsonnet/test/src-js/sjsonnet/FileTests.scala
sjsonnet/test/src-jvm/sjsonnet/FileTests.scala
sjsonnet/test/src-native/sjsonnet/FileTests.scala

I don't know why the `Make evalutator a simple val` made a difference, but it did.
We are back to the performance level of the scala3 migration (which is better than the 0.4 series)
```
Java HotSpot(TM) 64-Bit Server VM warning: -XX:ThreadPriorityPolicy=1 may require system level permission, e.g., being the root user. If the necessary permission is not possessed, changes to priority will be silently ignored.
Iteration   1: 218.122 ms/op
Iteration   2: 217.369 ms/op
Iteration   3: 216.576 ms/op
Iteration   4: 216.465 ms/op
Iteration   5: 215.468 ms/op
Iteration   6: 215.459 ms/op
Iteration   7: 215.341 ms/op
Iteration   8: 214.828 ms/op
Iteration   9: 215.898 ms/op
Iteration  10: 215.108 ms/op
Result "com.databricks.jsonnet.bundle.test.InternalJsonnetBuilderBenchmark.main":
216.063 …
```

Revert last changes that caused performance regressions

---

sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/src/sjsonnet/Parser.scala
sjsonnet/src/sjsonnet/ValScope.scala
sjsonnet/test/src-jvm/sjsonnet/ErrorTestsJvmOnly.scala
sjsonnet/test/src/sjsonnet/EvaluatorTests.scala

This PR fixes multiple bugs in object comprehensions (fixes #357, fixes #331, plus another bug).
Object comprehensions may define local variables and those variables may reference `self` or `super`.
Consider the reproduction reported in https://github.com/databricks/sjsonnet/issues/357:
```jsonnet
local lib = {
foo()::
{
local global = self,
[iterParam]: global.base {
foo: iterParam
}
for iterParam in ["foo"]
},
};
{
base:: {}
}
+ lib.foo()
```
This is supposed to output
```json
{
"foo": {
"foo": "foo"
}
}
```
but sjsonnet outputs
```
sjsonnet.Error: Field does not exist: base
at [Select base].(:7:26)
```
This bug occurs because of how bindings were managed: there's some tricky circular reference and variable rebinding logic (which I believe was added to handle references _between_ …

Fix multiple object comprehension bugs

---

build.sbt
build.sc
build_assets.sh

Update Scala 3 to 3.3.6

---

sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/src/sjsonnet/Std0150FunctionsTests.scala

Motivation:
Fix https://github.com/databricks/sjsonnet/issues/372
It should call `reverse` on the string when folding.

fix: Fix foldr for str

---

sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/src/sjsonnet/Format.scala
sjsonnet/src/sjsonnet/Materializer.scala
sjsonnet/src/sjsonnet/Parser.scala
sjsonnet/src/sjsonnet/StaticOptimizer.scala
sjsonnet/src/sjsonnet/Std.scala
sjsonnet/src/sjsonnet/StdRegex.scala
sjsonnet/src/sjsonnet/Val.scala
sjsonnet/src/sjsonnet/ValVisitor.scala

chore: Remove unused `new` when create Val.Arr

---

bench/src/main/scala/sjsonnet/ProfilingEvaluator.scala
sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/src/sjsonnet/Val.scala
sjsonnet/test/resources/test_suite/error.integer_conversion.jsonnet
sjsonnet/test/resources/test_suite/error.integer_left_shift.jsonnet
sjsonnet/test/resources/test_suite/error.integer_left_shift_runtime.jsonnet
sjsonnet/test/resources/test_suite/safe_integer_conversion.jsonnet
sjsonnet/test/src-js/sjsonnet/ErrorTests.scala
sjsonnet/test/src-jvm-native/ErrorTests.scala
sjsonnet/test/src/sjsonnet/Std0150FunctionsTests.scala

correct safe integer range for bitwise ops

---

build.sc

As we are only build the binary, it should be safe and faster without multi threading

chore: Turn off the multi threading support in scala native

---

build.mill

Motivation:
Better performance
refs: https://scala-native.org/en/stable/user/sbt.html#compilation-modes
Maybe because of the sjsonnet size is now from `7.2MB` to `12MB`
it's https://github.com/scalameta/scalafmt/blob/main/build.sbt#L342 ReleaseFull in scalafmt

chore: Change Scala native's release mode to ReleaseFull

---

sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/src/sjsonnet/StdMapTests.scala

In gojsonnet, a few functions of the stdlib accepts strings in addition to arrays. Sometimes this is mentioned in the stdlib documentation, sometimes it isn't - and importantly, this is a special property of a few select functions and it does NOT mean that a string can be treated as an array of single-character strings in every context with implicit type conversion between the two.
Eyeballing the gojsonnet code yields the following list of std functions which should support strings as parameters:
std.slice
std.member
std.map
std.flatMap
std.base64
Out of those, only `map` had missing support for strings, which is being added in this commit.
FTR, in the process, I discovered other quirks of the `map` function, such as the undocumented, `filterMap`-like behavior from this test case: …

Allow `std.map` to operate on string args as well.

---

build.mill

Both `js` and `native` projects are not being published at the moment

fix(publish): fix publishing for js and native projects

---

sjsonnet/test/resources/test_suite/format.jsonnet

Motivation:
It was missing in the previous commit.

chore: Uncomment missing `g` formatting test.

---

build.mill

Motivation:
Bump scala native to 0.5.8
https://github.com/scala-native/scala-native/releases/tag/v0.5.8
which may fix : https://github.com/databricks/sjsonnet/issues/374

chore: bump scala-native to 0.5.8

---

build.mill
readme.md
sjsonnet/src-js/sjsonnet/SjsonnetMain.scala

* Updated the JS entrypoint to allow usage from plain JS/TS, the previous version required an `Either` object which could not be returned from the JS side.
* Updated the documentation to reflect the changes.
* Compile the output as a CommonJS module to make import easier.

Update ScalaJS entrypoint and documentation

---

bench/src/main/scala/sjsonnet/MainBenchmark.scala
bench/src/main/scala/sjsonnet/MaterializerBenchmark.scala
bench/src/main/scala/sjsonnet/RunProfiler.scala
sjsonnet/src-jvm-native/sjsonnet/Config.scala
sjsonnet/src-jvm-native/sjsonnet/SjsonnetMain.scala

In the canonical implementation of jsonnet, the last match presented on -J wins (see
https://jsonnet-libs.github.io/jsonnet-training-course/lesson2.html#jsonnet_path for details). Given the current state is behavior is documented it's undesirable to simply change the implementation as that breaks backwards compatibility so the behavior is hidden behind a feature flag.

Add a flag to reverse the order of jpath entries.

---

sjsonnet/test/resources/go_test_suite/builtinRemoveAt2.golden
sjsonnet/test/resources/go_test_suite/builtinRemoveAt2.jsonnet 

Motivation:
Add a test for std.removeAt, which should not modify the parameter.
ported from go-jsonnet 
refs: https://github.com/google/go-jsonnet/pull/812

chore: Add test for std.removeAt which should not modify the parameter.

---

sjsonnet/src/sjsonnet/Std.scala

std.strReplaceAll is not standard, but can be drop-in replaced by std.native('regexGlobalReplace')

Remove std.strReplaceAll, which is not standard

---

sjsonnet/src-js/sjsonnet/Platform.scala
sjsonnet/src-native/sjsonnet/Platform.scala
sjsonnet/test/src/sjsonnet/ParseYamlTests.scala

Problem: std.parseYaml() produces incorrect results on the native and js targets when special characters are used; jvm is fine:
```
$ cat x.jsonnet
std.parseYaml(@'{"a":"\"\\n\n\r\f\b\t\u263A"}') { l: std.length(self.a) }
$ sjsonnet-908cc50a0760d42cd6136f07b2029fde97333c9c-jvm x.jsonnet
{
"a": "\"\\n\n\r\f\b\t☺",
"l": 9
}
$ sjsonnet-908cc50a0760d42cd6136f07b2029fde97333c9c-native x.jsonnet
{
"a": "\"\\\n\n\\r\\f\\b\\t\\u263A",
"l": 18
}
```
This PR fixes the native and js implementations and also adds the equivalent of x.jsonnet from the example above to the tests.

fix: Handling of special characters in std.parseYaml().

---

build.mill
sjsonnet/test/resources/go_test_suite/stdlib_smoke_test.jsonnet
sjsonnet/test/resources/go_test_suite/stdlib_smoke_test.jsonnet.golden
sjsonnet/test/src-jvm-native/sjsonnet/FileTests.scala
sjsonnet/test/src-jvm-native/sjsonnet/StdShasTests.scala

Add support for sha3 in native and fix the golden file for the smoke tests (double rounding error)

Remove last differences between jvm and native in regard to the go testsuite

---

sjsonnet/src/sjsonnet/YamlRenderer.scala
sjsonnet/test/src/sjsonnet/YamlRendererTests.scala

Problem: Empty lines are not indented properly in the YAML output:
```
$ { echo a; echo; echo b; } > file.txt
$ sjsonnet -e 'std.manifestYamlDoc({x:importstr "file.txt"},quote_keys=false)'
"x: |\n  a\n \n  b"
$ go-jsonnet -e 'std.manifestYamlDoc({x:importstr "file.txt"},quote_keys=false)'
"x: |\n  a\n  \n  b"
```

fix: Indentation of empty lines in YamlRenderer.

---

sjsonnet/src-js/sjsonnet/Platform.scala
sjsonnet/src-native/sjsonnet/Platform.scala
sjsonnet/test/src/sjsonnet/ParseYamlTests.scala

Problem: On js and native targets std.parseYaml() mishandles input where "---" is not at the beginning of the line. (The jvm target is fine.)
Fix: Only match "---" at the beginning of the line. Also don't require a newline after it.
Note that there are other corner cases that are still broken, but for those I'll file a bug against the underlying scala-yaml library.

fix(js,native): std.parseYaml() handling of "---".

---

sjsonnet/src-jvm-native/sjsonnet/SjsonnetMainBase.scala

This makes `/dev/stdin` work again in `--tla-code-file`, at least on the jvm target. See https://github.com/databricks/sjsonnet/issues/448
My https://github.com/databricks/sjsonnet/pull/432 broke it.
```
$ echo '{a:1}' | sjsonnet-0.5.2.jar --tla-code-file f=/dev/stdin -e 'function(f)f'
{
"a": 1
}
$ echo '{a:1}' | sjsonnet-master-36ecd2a7448d77b729786dd6336029475aba0eae.jar \
--debug-importer --tla-code-file f=/dev/stdin -e 'function(f)f'
[import /dev/stdin] candidate /dev/stdin
[import /dev/stdin] /dev/stdin is selected as it exists
[read OsPath(/dev/stdin)] file does not exist or is not a file
[read OsPath(/home/r/git/upstream/sjsonnet/<tla-var f>)] file does not exist or is not a file
Exception in thread "main" sjsonnet.Error: Couldn't import file: "/dev/stdin"
at [Import].(<tla-var f> …
```

fix(jvm): Let the importer read any path that exists and is not a directory.

---

sjsonnet/src/sjsonnet/ParseCache.scala

Motivation:
When try parsing an JSONnet script to expr, we may don't want to cache it.

chore: Add empty parse cache.

---

sjsonnet/src/sjsonnet/Error.scala

Motivation:
Make Error#formatError accept Throwable, and then I can use it elsewhere.

chore: Make Error#formatError accept Throwable.

---

build.mill

This PR fixes an issue in the Mill build that was stopped language/platform-specific suites like `FileTests` from being run, leading to a loss of test coverage (notably, the missing tests include the upstream golden file tests). 
I'm not a mill expert and am unsure if this is an _optimal_ fix, but empirically it seems to work based on the testing steps described below.
Prior to https://github.com/databricks/sjsonnet/pull/459, the JS and JVM tests both ran test suites that were defined in language-specific source directories (such as `FileTests`, which is defined in `src-js` and `src-jvm-native` directories rather than the shared `src` dir):
```bash
$ ./mill 'sjsonnet.js[2.13.16].test' 2>&1 | grep -E "(FileTests|go_test_suite|test_suite)" | head -3
[141] Checking …
```

Fix mill test sources issue that stopped language/platform-specific test suites from running

---

build.mill
sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/src/sjsonnet/Materializer.scala
sjsonnet/src/sjsonnet/Val.scala
sjsonnet/test/resources/go_test_suite/object_invariant_plus.jsonnet.golden
sjsonnet/test/src-js/sjsonnet/FileTests.scala
sjsonnet/test/src-jvm-native/sjsonnet/FileTests.scala
sjsonnet/test/src/sjsonnet/EvaluatorTests.scala

This PR files multiple assertion-related bugs:
- **Inheritance**:
-  https://github.com/databricks/sjsonnet/issues/439, where inherited object assertions would be skipped if assertions existed lower down in the object inheritance hierarchy (e.g. `{assert false} + {assert true}` would incorrectly pass because the inherited assertions would be skipped, whereas `{assert false} + {x: 2}` would fail because the child lacks its own assertions).
-  **Timing of assertion evaluation**: 
- Per the `object-index` rule [in the jsonnet spec](https://jsonnet.org/ref/spec.html#execution), accesses of an object member are supposed to require/trigger all object assertions, but `sjsonnet` was skipping this in certain cases. For example, `{assert false} + {x: 2}).x` fails in jsonnet / go-jsonnet but …

Fix multiple assertion related bugs (inheritance, binding of super in inherited assertions, and timing of evaluation)

---

build.mill

- Update mill to 1.0.3 and force to use the JVM version instead of the native version (issues in recent ubuntu -  https://github.com/com-lihaoyi/mill/issues/5508)
- compile statically by default in Linux

Fix scala native building issues and update mill

---

sjsonnet/src/sjsonnet/Std.scala
sjsonnet/test/graalvm/run_test_suites.py
sjsonnet/test/resources/go_test_suite/builtinBase64_invalid_byte_array.jsonnet.golden
sjsonnet/test/resources/go_test_suite/builtinBase64_invalid_byte_array1.jsonnet.golden
sjsonnet/test/resources/go_test_suite/builtinBase64_invalid_byte_array2.jsonnet.golden
sjsonnet/test/src-js/sjsonnet/FileTests.scala
sjsonnet/test/src-jvm-native/sjsonnet/FileTests.scala

This is an artificial limitation in go-jsonnet and we are not bound by it.
We are perfectly capable of encoding and decoding unicode strings.

Re-enable handling of unicode strings in std.base64

---

sjsonnet/src/sjsonnet/Settings.scala
sjsonnet/src/sjsonnet/Val.scala

Motivation:
It was missing, the `final` keyword.

chore: Add missing `final` to case classes.

---

sjsonnet/src/sjsonnet/Evaluator.scala
sjsonnet/src/sjsonnet/Materializer.scala
sjsonnet/src/sjsonnet/Std.scala
sjsonnet/src/sjsonnet/Util.scala
sjsonnet/src/sjsonnet/Val.scala
sjsonnet/test/src/sjsonnet/UnicodeHandlingTests.scala

**TL;DR**: sjsonnet string operations (length, indexing, ordering) were operating on UTF-16 code units (i.e. Java / Scala chars) but this is inconsistent with the jsonnet language reference, which [defines](https://jsonnet.org/ref/language.html#string) jsonnet strings as sequences of Unicode codepoints.
As a consequence, sjsonnet returned incorrect results (w.r.t. the go/c++ reference implementations) for several operations involving strings containing Unicode characters with codepoints outside of the [Basic Multilingual Plane](https://en.wikipedia.org/wiki/Plane_(Unicode)#Basic_Multilingual_Plane). 
For example, the string "🌍" consists of a single codepoint (`\u1F30D`, "earth globe europe-africa") and its UTF-16 representation is the surrogate pair `\uD83C\uDF0D`. In Java, this string …

Fix handling of non-BMP Unicode strings (jsonnet strings should operate over codepoints, not UTF-16 code units)
